### ISSUE TITLE
Update the `growth` module

### ISSUE THREAD

**Issue by GwennyGit** [draeger-lab/refinegems#104]
The `growth` module works and contains excellent ideas. However, a new and less confusing setup would be beneficial. The following ideas should improve the setup and add better handling of flux values.
***
### Main changes
- [x] Change existing functions:
  - [x] Rename `set_fluxes_to_simulate` -> `set_bounds_to_default`
    - [x] Change/add default parameter for upper & lower bound from COBRApy/user-specified
  - [x] Merge `get_default_uptake` (renamed to `get_model_uptake`) & `get_minimal_uptake` -> Name function `get_uptake`
  - [x] Replace `get_missing_exchanges` & `modify_medium` with `medium.add_medium_to_model`
  - [x] Merge `find_missing_essential` & `find_minimum_essential` -> `find_essential`**?**
  - [x] Further ideas for `medium.add_medium_to_model` -> ❗ name `changed to medium_to_model`:
    - [x] Integrate functionality of `find_essential` ❓ 
    - [x] Add a parameter to return the resulting medium
    - [x] Add the possibility to load medium as anaerobic ❓ 
    - [x] Extend usable namespaces from BiGG-specific to more namespaces
        - 🔴 this function can already do that, but not the wrappers in growth etc. -> see "still missing" below
  - [x] Rename `simulate_minimal_essential` -> `simulate_growth`
    - [x] Add parameter to enable growth with or without supplements
  - [x] Merge `growth_one_medium_from_default` & `growth_one_medium_from_minimal` -> `growth_on_one_medium`
  - [x] Check output of `growth_on_one_medium` & `get_growth_selected_media`
  - [x] Remove `get_growth_selected_media` -> Now handled by `medium.add_medium_to_model`!
- [x] Check connections in/to:
  - [x] `medium.py`
  - [x] `main.py`
  - [x] `SPECIMEN` (#99)
- [x] Check [pseudo algorithm](https://refinegems.readthedocs.io/en/latest/_images/growth_algorithm.png)
### Additional ideas
- [x] Check `model.optimize` & `model.slim_optimize` -> Possibility for faster run time?
- [x] `growth_on_one_medium`:
  - [x] Allow growth without supplementation -> default!
  - [x] Allow user-specified supplementation  -> #79
- [x] Add possibility to add:
  - [x] medium-specific fluxes from `medium2substance` table in `data.db`,
  - [x] default flux (Currently: 10),
  - [x] user-specific default flux and
  - [x] user-specific fluxes -> 🟠 oxygen percentage can be set only currently 
- [x] Improve handling of anaerobic simulations
### Isolated functions
- [x] Change function `get_default_secretion` -> **Wrong** description for what it currently really does!
- [x] ~~`get_all_minimum_essential` -> Do we need this? Is it correct? 🤔~~ -> Removed!
- [x] Rename `get_essential_reactions` -> `get_single_ko_essential_reacs` ❓ 
- [x] Rename `get_essential_reactions_via_bounds` -> `get_single_deletion_essential_reacs` ❓ 
- [x] Rename `find_additives` -> `find_additives_to_enhance_growth`/ `find_growth_enhancing_additives` ❓  
***
## Improvement/addition of new functions:
- [x] Add the possibility of changing carbon sources -> Function to variate carbon sources -> #79
- [x] namespace parameter or independency -> #79

### Still missing 
- [x] function for reading external media: missing a 'file' option 🟠 written, only needs testing
- [x] adding superoxide to a medium to enable growth e.g. important for Klebsiella (either via subset or new category to add different substances) -> #16

**Comment by cb-Hades** [comment]
`get_default_secretion` changed to one function for returning ID for reactions secreting compounds (`get_secretion`) and a second for for returning functions that produce a compound called `get_production`.

**Comment by cb-Hades** [comment]
Added functions to plot and save the growth simulation results.

**Comment by GwennyGit** [comment]
All tasks are either done or transferred to a new issue -- closing issue (#16, #79).
