### ISSUE TITLE
Revamping the module for filling gaps

### ISSUE THREAD

**Issue by GwennyGit** [draeger-lab/refinegems#126]
For the following reasons the module for gap-filling needs to be revamped:
- [SPECIMEN](https://github.com/draeger-lab/SPECIMEN)'s extension module and the module for gap filling within refineGEMs have some similarities/overlaps ($\rightarrow$ see https://github.com/draeger-lab/SPECIMEN/issues/9) and could, thus, be combined. 
- The gap-filling module within refineGEMs needs an overhaul with respect to some of its functionalities, as well as the overall set-ups ($\rightarrow$ see https://github.com/draeger-lab/refinegems/issues/52), and the same is true for the extension module in SPECIMEN ($\rightarrow$ see https://github.com/draeger-lab/SPECIMEN/issues/3).

---
### Todo:
- [x] 🗄️ Reorganise gap filling as class set-up
  - [x] Implement an abstract core class for gap analysis (`GapFiller`)
    - [x] Determine which methods should be abstract & which should be already fully implemented $\rightarrow$ Fill classes with information from the OG modules
    - [x] 📂 Output for gap analysis: Folder with several TSV/CSV files
  - [x] Implement one class per analysis set-up: `KEGGapFiller`, `BioCycGapFiller`, `GeneGapFiller`
    - [x] Fill classes with functionalities from the OG modules
  - [x] 💡 Separate class for gap filling instead of function [`gapfill_model`](https://github.com/draeger-lab/refinegems/blob/a84509b022533d24eeef263264798b60ef710fa4/src/refinegems/curation/gapfill.py#L148)
    - [x] 💡 Option to add either all new content from gap analysis to the model or restricted by namespace - for later
    - [x] ✍🏻 Report with statistics (+ some analyses?) 
- [x] ❗Realise improvements during revamping $\rightarrow$ https://github.com/draeger-lab/refinegems/issues/52
