### ISSUE TITLE
Update media definitions, document and extend db

### ISSUE THREAD

**Issue by famosab** [draeger-lab/refinegems#16]
I will collect the ToDos from this thread here @GwennyGit maybe you can mark what you did already and on what branch :D

- [x] remove CGXII and replace by CGXlab but rename to CGXII
- [x] remove LB and M9 without oxygen
- [x] ~~write function to simulate without oxygen~~ Add boolean to enable anaerobic growth simulation to all relevant functions
---
- [x] Re-evaluate all media in database:
   - [x] LB [[7]](#7)[[11]](#11)
   - [x] M9 [[6]](#6)
   - [x] CGXII [[4]](#4)
   - [x] SNM3 [[1]](#1)
   - ~~SMM~~
   - [x] RPMI [[3]](#3)
   - [x] CasA [[5]](#5)
   - [x] Blood [[9]](#9)
   - [x] ~~Urine~~ MP-AU [[10]](#10)
- [x] document all available media in the documentation
   - [x] Create RST file(s) for the media definitions 
   - [x] LB [[7]](#7)
   - [x] M9 [[6]](#6)
   - [x] CGXII [[4]](#4)
   - [x] SNM3 [[1]](#1)
   - ~~SMM~~
   - [x] RPMI [[3]](#3)
   - [x] CasA [[5]](#5)
   - [ ] Blood [[9]](#9) -> $\textcolor{red}{\text{Check where the Blood medium came from originally again!}}$
   - [x] ~~Urine~~ MP-AU [[10]](#10)
   - [x] dGMM [[8]](#8)
   - [x] SLM [[12]](#12) -> Artificial Sebum, Sweat & Basal medium belong to it!
   - [x] TSB
- [x] Document all available subsets in the documentation
   - [x] Create RST file(s) for the subset definitions
   - [x] CasA
   - [x] protAA
   - [x] artSe
- [x] Add page 'How to obtain an in sillico medium from a laboratory medium' to documentation 
- [x] Add Blood ~~[[2]](#2)~~ [[9]](#9)
- [x] ~~Add Urine [[2]](#2)~~ Add MP-AU [[10]](#10)
- [x] Add defined gut microbiota medium (dGMM) [[8]](#8)
- [x] Add SLM components [[12]](#12):
  - [x] Add Artificial Sweat to medium
  - [x] Add Artificial Sebum to subset
  - [x] Add Basal medium (Name from paper, Renamed to: BMS23 for Basal Medium Swaney 2023)
---
- [x] Add compound names to:
  - [x] RPMI
  - [x] SNM3
- [x] Add subsets:
  - [x] CasA - Contains only Casamino acids
  - [x] AA - Contains all proteinogenic amino acids 
  - [x] DiReM - Metabolites for the dissipation reactions
      - [x] already in: 'Water [H2O]', 'ATP [Adenosine triphosphate]','ADP','Hydrogen [H(+)]','Phosphate [PO4(3-)]',
        'CDP','GTP [Guanosine triphosphate]', 'GDP [Guanosine diphosphate]', 'UDP [Uridine 5-diphosphate]',
        'Nicotinamide adenine dinucleotide [NAD]', 'Nicotinamide adenine dinucleotide phosphate [NADP]',
        'Flavin adenine dinucleotide oxidized [FAD]', 'FMN [Flavin Mononucleotide]', 'D-Glucose',
        '2-Oxoglutarate [Oxoglutaric acid]', 'Ammonia'
      - [x] missing: 
        - [x] CTP 
        - [x] UTP
        - [x] ITP
        - [x] IDP
        - [x] NADH
        - [x] NADPH
        - [x] FADH2
        - [x] FMNH2
        - [x] Q8H2
        - [x] Q8
        - [x] MQL8
        - [x] MQN8
        - [x] 2DMMQL8
        - [x] 2DMMQ8
        - [x] ACCOA
        - [x] AC
        - [x] CoA
        - [x] DUPLICATE: Acetate and Acetate [Acetic acid] : remove the former + replace in subset, ....
      - [ ] 🔴 NOTE: these reactions are all about proton exchange, might lead to problems, since we usually ignore difference in protons .... in these cases it might be important to watch out for them - maybe also use this as a set to skip during duplicate removal, as this also includes protons differences
- [x] Check in `generate_insert_query` for strings in `value_string`❗ 
---
**Feature request for maintenance**
- [x] Add function to update tables/specific table entries automatically
---
- [ ] More database identifiers -> Check BiGG+VMH overlaps
- [x] Add superoxide ❗
- [ ] Add a definition for Tryptic Soy broth (TSB)
- [ ] Add a definition for Brain Heart Infusion (BHI)
***
<a id="1">[1]</a> 
Krismer, Bernhard; Liebeke, Manuel; Janek, Daniela; Nega, Mulugeta; Rautenberg, Maren; Hornig, Gabriele et al. (2014): Nutrient Limitation Governs Staphylococcus aureus Metabolism and Niche Adaptation in the Human Nose. In: PLOS Pathogens 10 (1), e1003862. DOI: 10.1371/journal.ppat.1003862.
<a id="2">[2]</a> 
Ding T, Case KA, Omolo MA, Reiland HA, Metz ZP, Diao X, Baumler DJ. Predicting Essential Metabolic Genome Content of Niche-Specific Enterobacterial Human Pathogens during Simulation of Host Environments. PLoS One. 2016 Feb 17;11(2):e0149423. doi: 10.1371/journal.pone.0149423. PMID: 26885654; PMCID: PMC4757543. 
<a id="3">[3]</a> 
https://www.thermofisher.com/de/de/home/technical-resources/media-formulation.114.html
<a id="4">[4]</a> 
Unthan, Simon, et al. "Beyond growth rate 0.6: What drives Corynebacterium glutamicum to higher growth rates in defined medium." Biotechnology and bioengineering 111.2 (2014): 359-371., [Preparation protocol](https://github.com/draeger-lab/C_striatum_wetlab/blob/main/supporting_experiments/metadata/PROTOCOL_CGXII_prep.md)
<a id="5">[5]</a> 
Richard A. Nolan (1971) Amino Acids and Growth Factors in Vitamin-Free Casamino Acids, Mycologia, 63:6, 1231-1234, DOI: [10.1080/00275514.1971.12019223](https://doi.org/10.1080/00275514.1971.12019223)
<a id="6">[6]</a> 
https://www.sigmaaldrich.com/DE/de/product/sigma/m6030, [Preparation protocol](https://github.com/draeger-lab/C_striatum_wetlab/blob/main/supporting_experiments/metadata/PROTOCOL_M9_prep.md)
<a id="7">[7]</a> 
Machado, Daniel, et al. "Fast automated reconstruction of genome-scale metabolic models for microbial species and communities." Nucleic acids research 46.15 (2018): 7542-7553.
https://carveme.readthedocs.io/en/latest/advanced.html#media-database
<a id="8">[8]</a>
Tramontano, M., Andrejev, S., Pruteanu, M. et al. Nutritional preferences of human gut bacteria reveal their metabolic idiosyncrasies. Nat Microbiol 3, 514–522 (2018). https://doi.org/10.1038/s41564-018-0123-9 
<a id="9">[9]</a>
Nantia Leonidou, Alina Renz, Reihaneh Mostolizadeh, and Andreas Dräger. New workflow predicts drug targets against sars-cov-2 via metabolic changes in infected cells. PLOS Computational Biology, 19(3):1–32, 03 2023. URL: https://doi.org/10.1371/journal.pcbi.1010903, [doi:10.1371/journal.pcbi.1010903](https://doi.org/10.1371/journal.pcbi.1010903).
<a id="10">[10]</a>
Sarigul, N., Korkmaz, F. & Kurultak, İ. A New Artificial Urine Protocol to Better Imitate Human Urine. Sci Rep 9, 20159 (2019). https://doi.org/10.1038/s41598-019-56693-4
<a id="11">[11]</a>
Oh, Y. K., Palsson, B. O., Park, S. M., Schilling, C. H., & Mahadevan, R. (2007). Genome-scale reconstruction of metabolic network in Bacillus subtilis based on high-throughput phenotyping and gene essentiality data. Journal of Biological Chemistry, 282(39), 28791-28799. https://doi.org/10.1074/jbc.M703759200
<a id="12">[12]</a>
Swaney MH, Nelsen A, Sandstrom S, Kalan LR. Sweat and Sebum Preferences of the Human Skin Microbiota. Microbiol Spectr. 2023 Feb 14;11(1):e0418022. doi: 10.1128/spectrum.04180-22. Epub 2023 Jan 5. PMID: 36602383; PMCID: PMC9927561

**Comment by GwennyGit** [comment]
While changing the database set-up for the media tables part, I noticed discrepancies between our media definitions in the documentation and those within the database.

For M9, this situation is easily resolvable as only the documentation table seems wrong.

For  LB, I am unsure how to resolve the issue. 
First, in the paper from Oh et al.[[1]](#1), it seems like `L-Cystin` is in the medium, while in the definition from CarveMe `L-Cysteine` is present. Should we add both? Or is one of them a mistake?
Second, in the paper from Oh et al.[[1]](#1), some components are not added to the LB definition as the _in silico_ definition was used for _Bacillus subtilis_, which had no transport system for this compound. At least, that is what the authors of the paper claim. In the same paper, they ‘mixed’ the compounds in Yeast extract and Tryptone to get the _in silico_ LB definition. Thus, I am unsure if we should include all their listed components (see [lb_coplex_def.txt](https://github.com/draeger-lab/refinegems/files/13178926/lb_coplex_def.txt)) or only the ones they have in their LB medium composition.
@cb-Hades, What is your opinion on that?

***
<a id="1">[1]<\a>
Oh, Y. K., Palsson, B. O., Park, S. M., Schilling, C. H., & Mahadevan, R. (2007). Genome-scale reconstruction of metabolic network in Bacillus subtilis based on high-throughput phenotyping and gene essentiality data. Journal of Biological Chemistry, 282(39), 28791-28799. https://doi.org/10.1074/jbc.M703759200

**Comment by cb-Hades** [comment]
Regarding Cystine/Cysteine, I found the following [explaination](https://www.xell.ag/de/rapid-oxidation-of-cysteine-to-cystine-in-aqueous-solutions-implications-for-spent-media-analysis/technical-notes-de/) about the oxidation of Cystein into Cystine in aqueous solutions. I would suggest putting in both. 

For the LB definition, I would also suggest using everything in the medium description, as other models could potentially have exchange reactions for the skipped substances.

**Comment by GwennyGit** [comment]
On the `dev` branch, `L-Cystathionine` was removed as it was wrongly added in the first place. In addition, `L-Cystine`, `nh3`, Iron, `Pyridoxal`, `Nicotinic acid` and a second identifier for D-Glucose were added as needed.

On the branch `database-io-connection`, `D-Malate` and `Hydrosulfide` were removed as these substances were not assigned to any media. In addition, `L-Cysteine` was changed to `L-Cystine` in the `RPMI` definition as `L-Cystine` is contained in the definition of thermofisher for `RPMI` but not `L-Cysteine`.

**Comment by GwennyGit** [comment]
No identifier in the BiGG database exists for Selenium. In addition, Selenium as such also makes no sense in a medium definition as it is not soluble in water (${\text{\textcolor{red}{Reference needs to be added here!}}}$). Moreover, as Selenium is mentioned as a substance in Yeast Extract in the article from Oh et al. [[11]](#11), which is used as a reference for the LB medium, we assume that the Selenium is not pure Selenium but Selenium containing substances produced by yeast. Furthermore, the Selenium mentioned in this paper could also be from an unused Selenium containing substance that is used in the growth medium of the yeast for the yeast extract. Thus, according to the article from Rayman [[12]](#12), the following components are Selenium containing substances in yeast extract:
Substance name | From yeast | From medium | BiGG identifier(s)
:--- | :---: | :---: | :---
Sodium selenite | ❌ | ✅ | `na1`, `slnt`
L-Selenomethionine [SeMet] | ✅ | ❌ | `selmeth`
Selenite | ✅ | ❌ | `slnt`
g-Glutamyl-Se-methylselenocysteine | ✅ | ❌ | `gglusem` <- same chemical formula
L-Adenosylselenohomocysteine [Se-adenosyl-Se-homocysteine] | ✅ | ❌ | `seahcys`

Hence, to the definition of `RPMI`, all these substances are added on `dev` and `database-io-connection`.

***
<a id="12">[12]</a>
Rayman, M. (2004). The use of high-selenium yeast to raise selenium status: How does it measure up? British Journal of Nutrition, 92(4), 557-573. doi:[10.1079/BJN20041251](https://doi.org/10.1079/BJN20041251)

**Comment by GwennyGit** [comment]
I started transferring the definition of ‘Artificial Sebum’ into an _in silico_ definition. 

For the substances ‘Olive oil’, ‘Coconut oil’ and ‘Cottonseed oil’, I used the [‘Design a diet’ tool](https://www.vmh.life/#nutrition/dietdesigner) on the VMH website. I selected each substance individually, generated the fluxes and downloaded the result. From the result, all components with zero flux were removed. For the flux generation, it was assumed that one litre of medium is used. Thus, the percentage provided in the original definition of ‘Artificial Sebum’ was multiplied by one litre. The result of this calculation was used to get the fluxes for the corresponding amount of substance.

The substance ‘Paraffin wax’ could not be mapped to any specific name, formula or database identifier. Hence, this substance is removed from the _in silico_ definition.

**Comment by GwennyGit** [comment]
A function to automatically extend the database or add missing entries would be great.
I tried to implement the functionality within the `add_medium` function of the `medium.py` module. However, my implementation was too basic, and I was unsure whether it would be better to have all the update functionality separately. 🤔
For now, I will use the interactive shell to add the entries for the source columns and update the substances as necessary. 
I will track the commit messages displayed in the shell in this comment for future automatic functionality.
---
Case 1 - Update a column in a table:
```sql
UPDATE "<table_name>" SET "<column_name>" = ? WHERE "rowid" = <rowid_of_row_with_correct_match>
```

**Comment by GwennyGit** [comment]
According to this [site](https://woelen.homescience.net/science/chem/solutions/fe.html), the iron oxidation states depend strongly on the surrounding pH. I need to investigate that further to conclude which media should contain which iron oxidation states.

**Comment by cb-Hades** [comment]
Database restructuring finished, namespace issues moved to #36 and ideas for new media have been added to #123
