### ISSUE TITLE
Enhance IO availability

### ISSUE THREAD

**Issue by GwennyGit** [draeger-lab/refinegems#60]
During the process of generating the `gapfill` module I restructured some code regarding parsing files and created the module `parse`. However, as @famosab stated in issue https://github.com/draeger-lab/refinegems/issues/52:
> So far I have added most parsing functions into `load` or (when it concerned CVTerms then into `cvterms` - maybe we should either rename load or merge parse into load?

It might be better to discuss the IO handling within refineGEMs in a new issue. 

**Reasoning for the module `parse`:**
I did introduce this module as I understood that `load` mostly contains IO handling for the models and is called `load` as it loads in data. Additionally, the GFF file parser for the KEGG analysis (`analysis_kegg`) was only available through the respective module. As @famosab and I discussed that a module containing all parsing related functions would make sense, I thought adding a new module called `parse` that does not handle loading files but handles the parsing would make sense.

**Regarding the quote from issue [52](https://github.com/draeger-lab/refinegems/issues/52):**
The main question is, do we want two modules, one for just loading in data and one for parsing input files or do we want one complete `IO` module. The `IO` module would make sense to have everything IO related at one place. However, it could get confusing if we have a lot of functions.
***
_Copied from comment https://github.com/draeger-lab/refinegems/issues/60#issuecomment-1424119013_
**TODO:**
- [x] Merge `gapfill-update` into dev
- [x] Merge `polish-update` into dev
- [x] Merge `sbo_update` into dev
- [x] Rename `load` to `io`
- [x] Remove duplicate `parse_fasta_headers`: 'create the pandas data frame containing the headers information required for both applications.
- [x] Transfer all functions in `parse` into `io`
- [x] Adjust links and imports for `load` and `parse` to `io` in all modules
- [x] Check whether all functions in `io` follow the naming idea `load_`, `parse_` and `write_`
- [x] Correct links in docs so that `io` is loaded instead of `load`
- [x] Refactor all functions related to parsing, loading, and writing from all modules to be included in `io`
- [x] `get_locus_gpr` to `parse_gff_for_gp_info`
- [x] Merge `get_name_from_locus_tag` with `get_name_locus_tag` in `polish` and rename to `search_ncbi_for_gpr`
- [x] Add new functions (see comment https://github.com/draeger-lab/refinegems/issues/60#issuecomment-1434287521):
  - [x] Function I: Adds a user-specified medium to data
  - [x] Function II: Extracts all media/a user-specified medium with the respective composition(s) as CSV file from data
  - [x] Add function for easier extension of the database with new columns/entries (e.g. to add identifiers from other databases) -> This is mainly considered for development.

**Comment by GwennyGit** [comment]
All tasks are done -- closing issue.
